#pragma once

#include <lvgl.h>

LV_FONT_DECLARE(NerdFonts_Regular_20);
LV_FONT_DECLARE(NerdFonts_Regular_40);

// Cyberpunk theme (generated by tools/cyberpunk_fonts.sh)
LV_FONT_DECLARE(cp_orbitron_22); // digits only
LV_FONT_DECLARE(cp_orbitron_34); // A-Z, 0-9, space, - and _
LV_FONT_DECLARE(cp_mono_10);
LV_FONT_DECLARE(cp_mono_12);
LV_FONT_DECLARE(cp_mono_14);
