/*
 * Bongo cat images: 4-bit indexed (index 0 transparent).
 * GENERATED by tools/bongo_cat_draw.py -- edit that, not this file.
 *
 * SPDX-License-Identifier: MIT
 */

#pragma once

#include <lvgl.h>

#define BONGO_W 96
#define BONGO_H 60
#define BONGO_PALETTE_BODY 2
#define BONGO_PALETTE_OUTLINE 3
#define BONGO_FRAME_DATA_SIZE 2944

extern const uint8_t bongo_idle_map[];
extern const lv_img_dsc_t bongo_idle;
extern const uint8_t bongo_left_map[];
extern const lv_img_dsc_t bongo_left;
extern const uint8_t bongo_right_map[];
extern const lv_img_dsc_t bongo_right;
extern const lv_img_dsc_t bongo_eyes_open;
#define BONGO_EYES_OPEN_X 36
#define BONGO_EYES_OPEN_Y 28
extern const lv_img_dsc_t bongo_eyes_closed;
#define BONGO_EYES_CLOSED_X 34
#define BONGO_EYES_CLOSED_Y 30
extern const lv_img_dsc_t bongo_mouth_smile;
#define BONGO_MOUTH_SMILE_X 44
#define BONGO_MOUTH_SMILE_Y 36
extern const lv_img_dsc_t bongo_mouth_frown;
#define BONGO_MOUTH_FROWN_X 44
#define BONGO_MOUTH_FROWN_Y 36
extern const lv_img_dsc_t bongo_sweat;
#define BONGO_SWEAT_X 74
#define BONGO_SWEAT_Y 16
extern const lv_img_dsc_t bongo_zzz;
#define BONGO_ZZZ_X 74
#define BONGO_ZZZ_Y 0
