#!/usr/bin/env python3
"""Draw the bongo cat frames and emit LVGL 4-bit indexed image data.

Run from the repo root:  python3 tools/bongo_cat_draw.py
Writes boards/shields/dongle_screen/src/widgets/bongo_cat_frames.c and
tools/bongo_cat_preview.png.
"""
from PIL import Image, ImageDraw

W, H, S = 48, 30, 2  # drawn at 48x30, scaled 2x -> 96x60
OUT_C = "boards/shields/dongle_screen/src/widgets/bongo_cat_frames.c"
OUT_PNG = "tools/bongo_cat_preview.png"

# index: (r, g, b, a) -- index 0 is transparent background
PALETTE = [
    (0, 0, 0, 0),          # 0 transparent
    (255, 255, 255, 255),  # 1 white (paws)
    (242, 165, 65, 255),   # 2 ginger (body)
    (196, 106, 27, 255),   # 3 dark ginger (outline, stripes)
    (255, 143, 171, 255),  # 4 pink (ears, cheeks, toe beans)
    (139, 90, 43, 255),    # 5 wood (desk)
    (20, 14, 10, 255),     # 6 near-black (eyes, mouth)
    (190, 140, 80, 255),   # 7 light wood (desk top edge)
]
TRANSPARENT, WHITE, GINGER, DARK, PINK, WOOD, INK, WOOD_LIGHT = range(8)


def base():
    im = Image.new("P", (W, H), TRANSPARENT)
    d = ImageDraw.Draw(im)
    d.polygon([(12, 12), (13, 3), (19, 8)], fill=GINGER, outline=DARK)   # left ear
    d.polygon([(35, 12), (34, 3), (28, 8)], fill=GINGER, outline=DARK)   # right ear
    d.point([(14, 6), (14, 7), (15, 8)], fill=PINK)
    d.point([(33, 6), (33, 7), (32, 8)], fill=PINK)
    d.chord([6, 6, 41, 46], 180, 360, fill=GINGER, outline=DARK)        # body
    for x in (21, 23, 24, 26):                                            # tabby stripes
        d.line([(x, 7), (x, 9 if x in (21, 26) else 10)], fill=DARK)
    d.rectangle([18, 14, 18, 15], fill=INK)                               # eyes
    d.rectangle([29, 14, 29, 15], fill=INK)
    d.point([(22, 18), (23, 19), (24, 19), (25, 18)], fill=INK)           # mouth
    d.point([(15, 17), (16, 17), (31, 17), (32, 17)], fill=PINK)          # cheeks
    d.line([(0, 26), (47, 26)], fill=WOOD_LIGHT)                          # desk
    d.rectangle([0, 27, 47, 28], fill=WOOD)
    return im, d


def paw_up(d, left):
    d.ellipse([8, 14, 15, 20] if left else [32, 14, 39, 20], fill=WHITE)
    d.point([(10, 16), (13, 16)] if left else [(34, 16), (37, 16)], fill=PINK)


def paw_down(d, left):
    d.ellipse([8, 22, 17, 28] if left else [30, 22, 39, 28], fill=WHITE)
    d.point([(11, 24), (14, 24)] if left else [(33, 24), (36, 24)], fill=PINK)


def frame(left_down, right_down):
    im, d = base()
    (paw_down if left_down else paw_up)(d, True)
    (paw_down if right_down else paw_up)(d, False)
    return im.resize((W * S, H * S), Image.NEAREST)


FRAMES = {"idle": frame(False, False), "left": frame(True, False), "right": frame(False, True)}


def to_c():
    out = [
        "/*\n * Bongo cat frames: 96x60, 4-bit indexed (index 0 transparent).\n"
        " * GENERATED by tools/bongo_cat_draw.py -- edit that, not this file.\n"
        " *\n * SPDX-License-Identifier: MIT\n */\n\n#include <lvgl.h>\n"
    ]
    for name, im in FRAMES.items():
        w, h = im.size
        px = im.load()
        data = []
        for r, g, b, a in PALETTE + [(0, 0, 0, 0)] * (16 - len(PALETTE)):
            data += [b, g, r, a]  # lv_color32_t byte order
        for y in range(h):
            for x in range(0, w, 2):
                data.append((px[x, y] << 4) | (px[x + 1, y] if x + 1 < w else 0))
        rows = [", ".join(f"0x{v:02x}" for v in data[i:i + 16]) for i in range(0, len(data), 16)]
        out.append(f"\nstatic const uint8_t bongo_{name}_map[] = {{\n    " + ",\n    ".join(rows) + ",\n};\n")
        out.append(
            f"\nconst lv_img_dsc_t bongo_{name} = {{\n"
            "    .header.cf = LV_IMG_CF_INDEXED_4BIT,\n"
            "    .header.always_zero = 0,\n"
            "    .header.reserved = 0,\n"
            f"    .header.w = {w},\n"
            f"    .header.h = {h},\n"
            f"    .data_size = sizeof(bongo_{name}_map),\n"
            f"    .data = bongo_{name}_map,\n}};\n"
        )
    open(OUT_C, "w").write("".join(out))


def preview():
    flat = [c for rgba in PALETTE for c in rgba[:3]]
    sheet = Image.new("RGB", (W * S * 3 + 20, H * S))
    for i, im in enumerate(FRAMES.values()):
        im = im.copy()
        im.putpalette(flat)
        sheet.paste(im.convert("RGB"), (i * (W * S + 10), 0))
    sheet.resize((sheet.width * 3, sheet.height * 3), Image.NEAREST).save(OUT_PNG)


if __name__ == "__main__":
    to_c()
    preview()
